[project]
name = "revyze-interview"
version = "0.1.0"
description = "Revyze coding interview"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.0.3",
    "ariadne>=0.23.0",
    "flask-cors>=4.0.1",
    "ruff>=0.6.2",
    "pytest>=8.3.2",
    "pydantic>=2.8.2",
]
